local M = { 'general.commands', desc = 'General functions and commands' }

local CM = require('adoyle-neovim-config.config')
local util = require('adoyle-neovim-config.util')

M.commands = {
	Q = { ':q!', { desc = 'quit current buffer without saving' } },
	Qa = { ':qa!', { desc = 'quit all buffers without saving' } },
	CD = { ':lcd %:p:h', { desc = 'Change PWD in current buffer' } },

	Cheatsheet = {
		function()
			local lang = table.unpack(vim.split(string.lower(vim.v.lang), '.', { plain = true }))
			local url = 'https://vim.rtorr.com/lang/' .. lang
			vim.fn['openbrowser#open'](url)
		end,
		{ desc = 'Open vim cheatsheet in browser' },
	},

	GetWinConfig = {
		function()
			vim.notify(vim.inspect(vim.api.nvim_win_get_config(0)))
		end,
		{ desc = 'Print current window config' },
	},

	FixLineBreak = {
		function()
			vim.cmd [[
				e ++ff=dos
				set ff=unix
				w
			]]
		end,
	},

	ProfileStart = {
		function()
			vim.cmd [[
				profile start profile.log
				profile func *
				profile file *
			]]
		end,
		{ desc = 'ProfileStart/ProfileEnd' },
	},

	ProfileEnd = {
		function()
			vim.cmd ':profile pause'
		end,
		{ desc = 'ProfileStart/ProfileEnd' },
	},

	OpenGithub = {
		function()
			local text = vim.fn.expand('<cfile>')
			vim.fn.OpenBrowser('https://github.com/' .. text)
		end,
		{ desc = 'Open github url in browser' },
	},

	ShowConfig = {
		function()
			local w = util.newWindow({ title = '[ADoyle-Neovim-Configs]', ft = 'lua' })
			local write = w.write
			write({ '-- The content generated by :ShowConfig', '-- config --' })

			local config = vim.tbl_extend('keep', CM.config, {})

			local lines = vim.split(vim.inspect(config), '\n')
			lines = vim.tbl_map(function(line)
				return line:gsub('<table %d+>', '"%1"'):gsub('<(%d+)>{', '--[[<table %1>--]]{'):gsub(
					'<function %d+>', '"%1"'):gsub('<metatable>', '["%1"]')
			end, lines)

			write(lines)

			w.resetCursor()
		end,
		{ desc = 'Show the merged config of adoyle-neovim-config' },
	},

	ShowPlugins = {
		function()
			local w = util.newWindow({ title = '[ADoyle-Neovim-Plugins]', ft = 'lua' })
			local write = w.write

			local P = require('adoyle-neovim-config.vim-plug')
			write('-- The content generated by :ShowPlugins')

			local disabledPlugs = {}
			local enabledPlugs = {}
			for _, p in pairs(P.plugs) do
				if p.disable then
					disabledPlugs[#disabledPlugs + 1] = p
				else
					enabledPlugs[#enabledPlugs + 1] = p
				end
			end

			local omitFields = { 'config', 'id' }
			local writePlug = function(p)
				write({ '', '-- id: ' .. p.id })

				local result = {}
				for key, val in pairs(p) do
					if not vim.tbl_contains(omitFields, key) then result[key] = val end
				end

				local lines = vim.split(vim.inspect(result), '\n')
				lines = vim.tbl_map(function(line)
					return line:gsub('<table %d+>', '"%1"'):gsub('<(%d+)>{', '--[[<table %1>--]]{'):gsub(
						'<function %d+>', '"%1"'):gsub('<metatable>', '["%1"]')
				end, lines)
				write(lines)
			end

			write('-- Disabled plugins --')
			for _, p in pairs(disabledPlugs) do writePlug(p) end

			write({ '', '-- Enabled plugins --' })
			for _, p in pairs(enabledPlugs) do writePlug(p) end

			w.resetCursor()
		end,
		{ desc = 'Show plugins of adoyle-neovim-config' },
	},

	ListSourcedScript = {
		function()
			local w = util.newWindow({ title = '[Nvim Sourced Scripts]' })
			local write = w.write
			write({ 'The content generated by :scriptnames', '' })

			local output = vim.api.nvim_exec('scriptnames', true)
			for _, l in pairs(vim.split(output, '\n')) do write(l) end

			w.resetCursor()
		end,
	},

	TabOrSpace = {
		function()
			vim.ui.select({ 'Tabs', 'Spaces' }, {
				prompt = 'Select Tabs or Spaces:',
				format_item = function(item)
					return 'I\'d like to choose ' .. item
				end,
			}, function(choice)
				if choice == 'Spaces' then
					vim.o.expandtab = true
				else
					vim.o.expandtab = false
				end
			end)
		end,
	},
}

return M
